ALTER TABLE tasks ADD COLUMN new_id UUID NULL;
UPDATE tasks SET new_id = CAST(LPAD(TO_HEX(id), 32, '0') AS UUID);
ALTER TABLE tasks DROP COLUMN id;
ALTER TABLE tasks RENAME COLUMN new_id TO id;
ALTER TABLE tasks ALTER COLUMN id SET NOT NULL;